application: ud859-go
module: default
version: v1

runtime: go
api_version: go1

handlers:
- url: /_ah/spi/.*
  script: _go_app
  secure: always

- url: /tasks/send_confirmation_email
  script: _go_app
  login: admin

- url: /((css|fonts|img|js|partials)/.+)$
  static_files: webapp/\1
  upload: webapp

- url: /
  static_files: webapp/index.html
  upload: webapp/index.html
