application: ud859
module: default
version: uno

runtime: go
api_version: go1

instance_class: B2

basic_scaling:
  max_instances: 5

handlers:
- url: /conference/v1/.*
  script: _go_app

- url: /((css|fonts|img|js|partials)/.+)$
  static_files: webapp/\1
  upload: webapp

- url: /
  static_files: webapp/index.html
  upload: webapp/index.html
